--person
CREATE TABLE PERSON(
    PERSON_ID VARCHAR(4),
    FIRST_NAME VARCHAR(255) NOT NULL,
    MIDDLE_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255) NOT NULL,
    P_ADDRESS VARCHAR(255),
    GENDER VARCHAR(25),
    DATE_OF_BIRTH DATE,
    PRIMARY KEY(PERSON_ID),
    CHECK (REGEXP_LIKE(PERSON_ID, '^P[0-9][0-9][0-9]$'))
);
--person_phone_number
CREATE TABLE PERSON_PHONE_NUMBER(
     PERSON_ID VARCHAR(4),
     PHONE_NUMBER VARCHAR(14) NOT NULL,
     PRIMARY KEY(PERSON_ID, PHONE_NUMBER),
     FOREIGN KEY(PERSON_ID) REFERENCES PERSON(PERSON_ID),
     UNIQUE(PHONE_NUMBER)
 );

CREATE TABLE AUTHOR (
AUTHOR_ID VARCHAR(15),
AUTHOR_NAME VARCHAR(255),
PERSON_ID VARCHAR(4) UNIQUE NOT NULL,
CHECK(REGEXP_LIKE(PERSON_ID, '^P[0-9][0-9][0-9]$')),
PRIMARY KEY(AUTHOR_ID),
FOREIGN KEY(PERSON_ID) REFERENCES PERSON(PERSON_ID));


 


--member
CREATE TABLE MEMBER(
    PERSON_ID VARCHAR(4),
    CARD_ID VARCHAR(15) NOT NULL,
    PRIMARY KEY(PERSON_ID),
    FOREIGN KEY(PERSON_ID) REFERENCES PERSON(PERSON_ID),
    FOREIGN KEY(CARD_ID) REFERENCES LIBRARY_CARD(CARD_ID)
);

--employee
CREATE TABLE EMPLOYEE(
PERSON_ID VARCHAR(4),
START_DATE DATE NOT NULL,
DESIGNATION VARCHAR(25) NOT NULL,
PRIMARY KEY(PERSON_ID),
FOREIGN KEY(PERSON_ID) REFERENCES PERSON(PERSON_ID)
);

--receptionist
CREATE TABLE RECEPTIONIST(
    PERSON_ID VARCHAR(4),
    TRAINER_ID VARCHAR(8),
    PRIMARY KEY(PERSON_ID),
    FOREIGN KEY(PERSON_ID) REFERENCES EMPLOYEE(PERSON_ID),
    FOREIGN KEY(TRAINER_ID) REFERENCES TRAINER(TRAINER_ID)
);


CREATE TABLE IF NOT EXISTS WONDER_LIBRARY.PAYMENT
(   
    PAYMENT_ID              VARCHAR(50)     NOT NULL,
    RECEPTIONIST_ID         VARCHAR(20)     NOT NULL,
    MEMBER_ID               VARCHAR(20)     NOT NULL,
    ISSUE_DATE              DATE            NULL,
    DUE_DATE                DATE GENERATED ALWAYS AS (ISSUE_DATE + INTERVAL 30 DAY) NULL,
    PAYMENT_METHOD          VARCHAR(20)     NULL,
    PAYMENT_TIME            DATETIME        NOT NULL,
    AMOUNT                  DECIMAL(10,2)   NOT NULL,
    
    PRIMARY KEY (PAYMENT_ID),
    FOREIGN KEY(RECEPTIONIST_ID) REFERENCES WONDER_LIBRARY.RECEPTIONIST(PERSON_ID)
);

CREATE TABLE IF NOT EXISTS WONDER_LIBRARY.BOOK_ISSUE
(   
    BOOK_ID     VARCHAR(20)     NOT NULL,
    MEMBER_ID   VARCHAR(20)     NOT NULL,
    ISSUE_DATE  DATE        NOT NULL,
    PAYMENT_ID  VARCHAR(50)     NULL,
    PRIMARY KEY(BOOK_ID, MEMBER_ID, ISSUE_DATE),
    FOREIGN KEY(PAYMENT_ID) REFERENCES WONDER_LIBRARY.PAYMENT(PAYMENT_ID),
    FOREIGN KEY(MEMBER_ID) REFERENCES WONDER_LIBRARY.MEMBER(PERSON_ID)
);

CREATE TABLE IF NOT EXISTS WONDER_LIBRARY.BOOK_CATALOG
(
    BOOK_ID     VARCHAR(20)     NOT NULL,
    DATE        DATE            NOT NULL,
    CATALOGING_MANAGER_ID   VARCHAR(20) NOT NULL,
    PRIMARY KEY(BOOK_ID, DATE)
);

CREATE TABLE IF NOT EXISTS WONDER_LIBRARY.BOOK_CATEGORY
(
    BOOK_ID     VARCHAR(20)     NOT NULL,
    CATEGORY    VARCHAR(20)     NOT NULL,
    PRIMARY KEY(BOOK_ID)
);

CREATE TABLE IF NOT EXISTS WONDER_LIBRARY.PUBLISHER
(
    PUBLISHER_ID         VARCHAR(20)    NOT NULL,
    PUBLISHER_NAME       VARCHAR(255)   NOT NULL,
    ADDRESS              VARCHAR(255)   NOT NULL,     
    EMAIL                VARCHAR(100)   NOT NULL,
    CONTACT              VARCHAR(14)    NOT NULL,
    PRIMARY KEY (PUBLISHER_ID)
);

CREATE TABLE IF NOT EXISTS WONDER_LIBRARY.BOOKS
(
    BOOK_ID         VARCHAR(20),
    BOOK_TITLE      VARCHAR(255)   NOT NULL,
    BOOK_EDITION    VARCHAR(50)    NOT NULL,     
    PUBLISHER_ID    VARCHAR(20)    NOT NULL,
    CATEGORY        VARCHAR(20)    NOT NULL,
    PRIMARY KEY (BOOK_ID)
    FOREIGN KEY(PUBLISHER_ID) REFERENCES WONDER_LIBRARY.PUBLISHER(PUBLISHER_ID)
);

CREATE TABLE IF NOT EXISTS WONDER_LIBRARY.WRITES_BOOK
(
    BOOK_ID     VARCHAR(20),
    AUTHOR_ID   VARCHAR(20),
    PRIMARY KEY (BOOK_ID, AUTHOR_ID),
    FOREIGN KEY(AUTHOR_ID) REFERENCES WONDER_LIBRARY.AUTHOR(AUTHOR_ID),
    FOREIGN KEY(BOOK_ID)   REFERENCES WONDER_LIBRARY.BOOKS(BOOK_ID)
);

CREATE TABLE IF NOT EXISTS WONDER_LIBRARY.COMMENTS
(
    COMMENT_ID     VARCHAR(20),
    COMMENT_TIME   DATETIME      NOT NULL,
    COMMENT_TEXT   VARCHAR(255)     NULL,
    RATING_SCORE   INTEGER          NULL,
    PERSON_ID      VARCHAR(20)      NOT NULL,
    BOOK_ID        VARCHAR(20)      NOT NULL,
    PRIMARY KEY (COMMENT_ID),
    FOREIGN KEY (PERSON_ID) REFERENCES WONDER_LIBRARY.PERSON(PERSON_ID),
    FOREIGN KEY (BOOK_ID) REFERENCES WONDER_LIBRARY.BOOKS(BOOK_ID),
    CHECK (RATING_SCORE <= 5)
);