CREATE OR REPLACE VIEW TopGoldMember AS
SELECT P.FIRST_NAME, P.LAST_NAME, LC.DATE_OF_ISSUE
FROM
(SELECT BI.MEMBER_ID AS PERSON_ID
FROM BOOK_ISSUE BI
WHERE BI.ISSUE_DATE >= (CURRENT_DATE - INTERVAL 1 MONTH)
GROUP BY BI.MEMBER_ID
HAVING COUNT(DISTINCT BI.BOOK_ID) > 0) TOP
LEFT JOIN PERSON P ON TOP.PERSON_ID = P.PERSON_ID 
LEFT JOIN MEMBER M ON TOP.PERSON_ID = M.PERSON_ID
LEFT JOIN LIBRARY_CARD LC ON M.CARD_ID = LC.CARD_ID;

CREATE OR REPLACE VIEW PopularBooks AS
SELECT BOOKS.*, BORROWED_COUNT
FROM
(SELECT BOOK_ID, COUNT(1) BORROWED_COUNT
FROM BOOK_ISSUE
WHERE ISSUE_DATE >= (CURRENT_DATE - INTERVAL 1 YEAR)
GROUP BY BOOK_ID) BORROWED
LEFT JOIN BOOKS ON BORROWED.BOOK_ID = BOOKS.BOOK_ID
ORDER BY BORROWED_COUNT DESC;

CREATE OR REPLACE VIEW BestRatingPublisher AS
SELECT PUBLISHER_NAME
FROM PUBLISHER
WHERE PUBLISHER_ID NOT IN
(SELECT DISTINCT PUBLISHER_ID FROM
	(SELECT C.BOOK_ID, B.PUBLISHER_ID, AVG(RATING_SCORE) AS AVG_SCORE
	FROM COMMENTS C
	LEFT JOIN BOOKS B ON C.BOOK_ID = B.BOOK_ID
	GROUP BY C.BOOK_ID, B.PUBLISHER_ID) RATING
    WHERE AVG_SCORE < 4
);